CREATE TABLE product (
  id INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  PRICE NUMERIC,
  IMAGE TEXT NOT NULL
)
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name Text NOT NULL,
  place TEXT,
  payment TEXT,
  cart INTEGER
)
