import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css"; 
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dropshiping shop",
  description: "Generated by create next app",
};

const CartIcon = () => (
  <Link href="/cart">
    <img
      src="/cart.svg"  
      alt="Home Icon"
      width="32"
      height="32"
    />
  </Link>
);

const UserIcon = () => (
  <Link href="/user">
    <img
      src="/user.svg"  
      alt="Home Icon"
      width="32"
      height="32"
    />
  </Link>
);

const SearchIcon = ({onClick}) => (
    <img
      src="/search.svg"  
      alt="Home Icon"
      width="32"
      height="32"
      onClick={onClick}
    />
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
            <title>Hello, world!</title>    
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <div className={styles.topBar}>
                <Link href="/">
                    <p className={styles.headLine}>Shop</p>
                </Link>
                
                <input placeholder="Searh..." className={styles.textField}>
                </input>
                <SearchIcon></SearchIcon>
                <UserIcon></UserIcon>
                <CartIcon></CartIcon>
            </div>
        {children}
        </body>
    </html>
  );
}